### PR TITLE
Deleted empty LoginController

### PR DESCRIPTION
**Pull request by nachoa88**
Just deleted an empty LoginController because the logic of this controller is being managed by AuthController.

### CODE REVIEW

**Review by jordimorillo — APPROVED** [review]
Welcome onboard!

**Comment by JustTheDude001** [comment]
Best Onboarding ever! Amazing Job!

**Review by JustTheDude001 — APPROVED** [review]
Best Onboarding ever! Great Job!

**Review by begoIT24 — APPROVED** [review]
Thanks @nachoa88 and @jordimorillo for fixing this

**Pull request merged**
